Update to 1.4.0

diff --git a/.github/actions/multistrap/action.yml b/.github/actions/multistrap/action.yml
--- a/.github/actions/multistrap/action.yml
+++ b/.github/actions/multistrap/action.yml
@@ -4,6 +4,11 @@ inputs:
   arch:
     description: "Target arch"
     required: true
+    default: ""
+  pyver:
+    description: "Python version"
+    required: false
+    default: ""
   packages:
     description: "Extra packages to install"
     required: false
@@ -19,6 +24,9 @@ runs:
     - id: create_chroot
       run: |
         set -xe
+        
+        echo "arch input parameter: "${{ inputs.arch }}""
+        echo "pyver input parameter: "${{ inputs.pyver }}""
 
         multistrap_conf=""
         if [ "${{ inputs.arch }}" = "armv7" ]; then
@@ -28,8 +36,29 @@ runs:
         if [ "${{ inputs.arch }}" = "aarch64" ]; then
           multistrap_conf=multistrap_armbian64_buster.conf
         fi
+        if [ "${{ inputs.arch }}" = "armv7" ] && [ "${{ inputs.pyver }}" = "3.7" ]; then
+          multistrap_conf=multistrap_raspbian_buster.conf
+        fi
+        if [ "${{ inputs.arch }}" = "armv7" ] && [ "${{ inputs.pyver }}" = "3.9" ]; then
+          multistrap_conf=multistrap_raspbian_bullseye.conf
+        fi
+        if [ "${{ inputs.arch }}" = "aarch64" ] && [ "${{ inputs.pyver }}" = "3.7" ]; then
+          multistrap_conf=multistrap_armbian64_buster.conf
+        fi
+        if [ "${{ inputs.arch }}" = "aarch64" ] && [ "${{ inputs.pyver }}" = "3.9" ]; then
+          multistrap_conf=multistrap_armbian64_bullseye.conf
+        fi
+        if [ "${{ inputs.arch }}" = "" ] && [ "${{ inputs.pyver }}" = "" ]; then
+          echo "Either arch or pyver input parameters needs to be provided"
+          exit 1
+        fi
 
-        multistrap -d ${{ env.SYSTEM_RASPBIAN }} -f ${{ github.workspace }}/native_client/${multistrap_conf}
+        # Retry 2 times because Rasbian mirrors are often failing
+        if ! multistrap -d ${{ env.SYSTEM_RASPBIAN }} -f ${{ github.workspace }}/native_client/${multistrap_conf}; then
+          if ! multistrap -d ${{ env.SYSTEM_RASPBIAN }} -f ${{ github.workspace }}/native_client/${multistrap_conf}; then
+            multistrap -d ${{ env.SYSTEM_RASPBIAN }} -f ${{ github.workspace }}/native_client/${multistrap_conf}
+          fi
+        fi
 
         if [ ! -z "${{ inputs.packages }}" ]; then
           TO_MOUNT=${{ github.workspace }}
